### ISSUE TITLE
Fix build error

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/raket#15]
Since [this commit](https://github.com/richelbilderbeek/raket/commit/b7322bb9572e5ab75366140fb1bfc0d8e4d0126e) the build is broken.

H0: it is lack of Roxygen2: REJECTED
H1: it is upstream: start test

**Comment by richelbilderbeek** [comment]
If H1 ('it is upstream') is true, a trigger of this build will cause the clean build to fail

![before](https://user-images.githubusercontent.com/2098230/40110718-05683758-5901-11e8-8808-cfcf807afd5e.png)

**Comment by richelbilderbeek** [comment]
It *is* upstream:

![after](https://user-images.githubusercontent.com/2098230/40111096-1cf8f172-5902-11e8-9094-0f85b67e7cb6.png)

**Comment by J-Damhuis** [comment]
I assume there is nothing we can do then?

**Comment by richelbilderbeek** [comment]
It means that 

 * all of us (@Tomdkkr) need to check our code locally (using 'Check') before pushing
 * I will Google and fix it. You may volunteer to Google along, if and only if there is time
 * If upstream works again, we'll have to mend the pieces together again

**Comment by richelbilderbeek** [comment]
Hmmm, that now-failing-build has [a different error message](https://travis-ci.org/richelbilderbeek/raket/builds/379227064#L523).

Will reset caching in .travis.yml

**Comment by richelbilderbeek** [comment]
No need to reset cache: AppVeyor fails as well.

Did something bold instead: merge everything with master. :rainbow_flag: not exactly wise :rainbow_flag:.

**Comment by richelbilderbeek** [comment]
Packages that join the crashing mood:

 * [beastier](https://github.com/richelbilderbeek/beastier)

**Comment by richelbilderbeek** [comment]
Ah, it is [a known Issue that is worked on](https://github.com/travis-ci/travis-ci/issues/9625)

**Comment by richelbilderbeek** [comment]
OK, the build error appears fixed.

New error:

```
Quitting from lines 96-101 (demo.Rmd) 
Error: processing vignette 'demo.Rmd' failed with diagnostics:
attempt to set an attribute on NULL
Execution halted
```

**Comment by richelbilderbeek** [comment]
Fixed that error with a workaround, error is in `rkt_plot` being called in the demo vignette.

**Comment by richelbilderbeek** [comment]
@J-Damhuis or @Tomdkkr:if the lintr-bot errors annoy you, feel encouraged to clean them up (of course: we should usually clean up our own mess). I will do so myself after submitting my babette article as a Microsoft Word :sob: document, as that has absolute priority.
