### ISSUE TITLE
Fix test

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/raket#16]
The [last build breaks](https://travis-ci.org/richelbilderbeek/raket/builds/380159987): the documentation was not completed. 

@J-Damhuis: can I assume you will also fix that? I know there are a lot of 'trivial' errors on your plate now, but, well, that helps you develop to a pro developer :+1:

If yes, you can assign yourself at the right of this text, at 'Assignees'.

**Comment by J-Damhuis** [comment]
Already pushed a fix (at least I hope I fixed it)

**Comment by richelbilderbeek** [comment]
Awesome! This Issue can be closed if and only if the build passes. Feel encouraged to do so.

**Comment by J-Damhuis** [comment]
Fixed!
