### ISSUE TITLE
Problems installing Rtools on R 3.5.0 on Windows 7

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/raket#22]
From @Giappo:

I am trying to install raket but I keep on getting the error message
complaining about Rtools version like:
- install.packages("Rtools"); library(Rtools)
Installing package into ‘C:/Users/P274829/Documents/R/win-library/3.5’
(as ‘lib’ is unspecified)
Warning in install.packages :
package ‘Rtools’ is not available (for R version 3.5.0)
Warning in install.packages :
unable to access index for repository
http://www.stats.ox.ac.uk/pub/RWin/bin/windows/contrib/3.5:
cannot open URL
'http://www.stats.ox.ac.uk/pub/RWin/bin/windows/contrib/3.5/PACKAGES'
Error in library(Rtools) : there is no package called ‘Rtools’

Or, using some workaround found on internet, the best I can get is:
- "Downloading GitHub repo richelbilderbeek/tracerer@master
from URL
https://api.github.com/repos/richelbilderbeek/tracerer/zipball/master
WARNING: Rtools is required to build R packages, but no version of
Rtools compatible with R 3.5.0 was found. (Only the following
incompatible version(s) of Rtools were found:3.3,3.4)

Please download and install Rtools 3.5 from
http://cran.r-project.org/bin/windows/Rtools/.
Installation failed: Could not find build tools necessary to build tracerer"

Do you know how to solve this?

**Comment by richelbilderbeek** [comment]
The R mirror (at http://www.stats.ox.ac.uk/ ) was down apparently. Try again
now, or use a different mirror, for example, the main R repo:

```
install.packages("Rtools", repos='http://cran.us.r-project.org')
```

**Comment by richelbilderbeek** [comment]
Reply from @Giappo:

Sorry but it keeps on giving me the same error:
"Warning in install.packages : package ‘Rtools’ is not available (for
R version 3.5.0)"

Is there any other way? Do you know about any other people having
problems installing raket?

**Comment by richelbilderbeek** [comment]
Installing a basic R package like Rtools has nothing to do with any package that is dependent on it. What may help is send me the new, full error message, so that I can highlight the line you did not read :-)

**Comment by richelbilderbeek** [comment]
Reply from @Giappo:

I found the way. It needs to be downloaded manually from here
"https://cran.r-project.org/bin/windows/Rtools/" with the latest
version, then installed ticking the PATH thingy and then rebooting R.
In case someone else will find the same problem you can tell them to
do so.

PS: I also had problem with the dependency "xmlparsedata" so I had to
run manually "install.packages('xmlparsedata')".

**Comment by richelbilderbeek** [comment]
Thanks for sharing, happy that you got it to work!

**Comment by port1a** [comment]
Thanks a lot guys
